// Auto-generated by make — do not edit
let buildVersion = "0.6.33"
let buildCommit = "468eace"
let buildBranch = "main"
let buildDate = "2026-04-03 23:27:57 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3.1"
