// Auto-generated by make — do not edit
let buildVersion = "0.8.7"
let buildCommit = "3825cf9"
let buildBranch = "main"
let buildDate = "2026-04-06 12:07:44 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3.1"
