// Auto-generated by make — do not edit
let buildVersion = "0.6.29"
let buildCommit = "8cc0c09"
let buildBranch = "main"
let buildDate = "2026-04-03 20:20:41 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3.1"
